// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnlbarxhgaplqkshtnks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ubGJhcnhoZ2FwbHFrc2h0bmtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MzQ0NzQsImV4cCI6MjA3NDAxMDQ3NH0.c3qkiexi5-yzuaeONocQ6_vSxz02ILnEbsZCwUIcV4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});